version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
      - redis
    env_file:
      - .env
    volumes:
      - .:/code
    command: gunicorn vschools.wsgi:application -b 0.0.0.0:8000
    ports:
    - "8000:8000"
    networks:
    - net


  postgres_db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    expose:
     - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
    - net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - net
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - net

  daphne:
    build: .
    command: /root/env/bin/python /root/env/bin/daphne -e ssl:8001:privateKey=/etc/letsencrypt/live/vschoolsmeet.tech/privkey.pem:certKey=/etc/letsencrypt/live/vschoolsmeet.tech/fullchain.pem vschools.asgi:application
    depends_on:
      - postgres_db
      - redis
    networks:
      - net
    ports:
     - "8001:8001"

  janus:
    image: janusgateway/janus
    ports:
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "8189:8189"
    networks:
      - net

networks:
  net:
    driver: bridge


volumes:
  postgres_data: