FROM python:3
RUN apt-get update && \
    apt-get install -y build-essential zliblg-dev automake autoconf libtool subversion git

RUN apt-get install -y g++ make libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config

RUN git clone https://github.com/kaldi-asr/kaldi.git /opt/kaldi --depth=1
    
RUN cd opt/kaldi/tools && \
    extras/check_dependencies.sh && \
    make -j $(nproc) && \
    cd ../src && ./configure --shared && \
    make -j &(nproc) depend && \
    make -j $(nproc) pykaldi

ENV PYTHONPATH=/opt/kaldi/src/pykaldi:$PYTHONPATH

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/