FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN mkdir /code
WORKDIR /code
RUN python3 -m venv /code/environment

COPY . /code/

RUN /code/environment/bin/pip install pip --upgrade && \
    /code/environment/bin/pip install -requirements.txt

CMD ["/code/entrypoint.sh"]