# Generated by Django 4.2 on 2023-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='DaysOfWeek',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='WeeksOfMonth',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
