# Generated by Django 3.1.5 on 2021-05-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='USER',
            new_name='user',
        ),
    ]
