# Generated by Django 3.1.5 on 2021-05-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210507_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='datejoined',
            field=models.DateField(blank=True),
        ),
    ]
