# Generated by Django 4.1.9 on 2023-11-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='webauthn_challenge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
