# Generated by Django 3.2.3 on 2022-11-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_recordedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account_info',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account_info',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
