# Generated by Django 3.2.3 on 2022-12-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20221120_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.TextField(null=True, unique=True),
        ),
    ]
