# Generated by Django 3.2.3 on 2022-12-27 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_room_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', unique=True)),
            ],
        ),
    ]
