# Generated by Django 3.2.3 on 2022-12-27 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_room_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_recording',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
    ]
