# Generated by Django 3.2.3 on 2023-01-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_raised_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_message',
            name='raised_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Raised_hand',
        ),
    ]
