# Generated by Django 3.2.3 on 2023-01-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20230103_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_message',
            name='raised_hand',
        ),
        migrations.AddField(
            model_name='room_member',
            name='raised_hand',
            field=models.BooleanField(default=False),
        ),
    ]
