# Generated by Django 3.2.3 on 2023-01-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20230103_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_member',
            name='raised_hand',
        ),
    ]
