# Generated by Django 3.2.3 on 2023-02-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_room_member_raised_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_member',
            name='hand_raised',
            field=models.BooleanField(default=False),
        ),
    ]
