# Generated by Django 3.2.3 on 2023-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_room_member_hand_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='profile_picture',
            field=models.ImageField(blank=True, default='no_profile_Pic.svg', upload_to='profile_pics'),
        ),
    ]
